# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ISOchangetool.py
# Created on: 2018-12-05 18:28:21.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Output_signature_file = ""
Output_signature_file__2_ = ""
Output_classified_raster = "C:\\Users\\YLUCA8469\\Documents\\ArcGIS\\Default.gdb\\isocluster"
Reclass_isoc1 = "C:\\Users\\YLUCA8469\\Documents\\ArcGIS\\Default.gdb\\Reclass_isoc1"
Output_classified_raster__2_ = "C:\\Users\\YLUCA8469\\Documents\\ArcGIS\\Default.gdb\\isocluster1"
Reclass_isoc2 = "C:\\Users\\YLUCA8469\\Documents\\ArcGIS\\Default.gdb\\Reclass_isoc2"
Plus_Reclass1 = "C:\\Users\\YLUCA8469\\Documents\\ArcGIS\\Default.gdb\\Plus_Reclass1"

# Process: Iso Cluster Unsupervised Classification
arcpy.gp.IsoClusterUnsupervisedClassification_sa("", "", Output_classified_raster, "20", "10", Output_signature_file)

# Process: Iso Cluster Unsupervised Classification (2)
arcpy.gp.IsoClusterUnsupervisedClassification_sa("", "", Output_classified_raster__2_, "20", "10", Output_signature_file__2_)

# Process: Reclassify
arcpy.gp.Reclassify_sa(Output_classified_raster, "VALUE", "", Reclass_isoc1, "DATA")

# Process: Reclassify (2)
arcpy.gp.Reclassify_sa(Output_classified_raster__2_, "VALUE", "", Reclass_isoc2, "DATA")

# Process: Plus
arcpy.gp.Plus_sa(Reclass_isoc1, Reclass_isoc2, Plus_Reclass1)


